# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96d3f061a0312fd182ee0c3a17ef3197aa58744e720db5e0e6ab59cc3e6a7ffb1646b0fcc263b49021910bdbfb2feaa08afd290a899a5add36558bdaa74c9632

test:
  secret_key_base: 141d0a36e4b8f88dfcaf003135f604cb41dbfde1c9a8673dbff35f04f4be1c247cfd2be7f3772d89d7d6cba195d3d60e370ec76996bb0e335fb2dc4428d1f1fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
